// lib/utils/currency_data.dart

final Map<String, String> currencyNames = {
  'USD': 'Dólar Americano',
  'BRL': 'Real Brasileiro',
  'EUR': 'Euro',
  'GBP': 'Libra Esterlina',
  'JPY': 'Iene Japonês',
  'CAD': 'Dólar Canadense',
  'AUD': 'Dólar Australiano',
  'CHF': 'Franco Suíço',
  'CNY': 'Yuan Chinês',
  'ARS': 'Peso Argentino',
  'MXN': 'Peso Mexicano',
  'CLP': 'Peso Chileno',
  'COP': 'Peso Colombiano',
  'UYU': 'Peso Uruguaio',
  'PYG': 'Guarani Paraguaio',
  'PEN': 'Sol Peruano',
  'BOB': 'Boliviano',
  'VES': 'Bolívar Soberano Venezuelano',
  'AED': 'Dirham dos Emirados Árabes Unidos',
  'AFN': 'Afegane Afegão',
  'ALL': 'Lek Albanês',
  'AMD': 'Dram Armênio',
  'ANG': 'Florim das Antilhas Holandesas',
  'AOA': 'Kwanza Angolano',
  // ignore: equal_keys_in_map
  'AUD': 'Dólar Australiano',
  'AWG': 'Florim Arubano',
  'AZN': 'Manat Azerbaijano',
  'BAM': 'Marco Conversível da Bósnia e Herzegovina',
  'BBD': 'Dólar de Barbados',
  'BDT': 'Taka de Bangladesh',
  'BGN': 'Lev Búlgaro',
  'BHD': 'Dinar do Bahrein',
  'BIF': 'Franco Burundinês',
  'BMD': 'Dólar Bermudense',
  'BND': 'Dólar de Brunei',
  // ignore: equal_keys_in_map
  'BOB': 'Boliviano',
  // ignore: equal_keys_in_map
  'BRL': 'Real Brasileiro',
  'BSD': 'Dólar das Bahamas',
  'BTN': 'Ngultrum do Butão',
  'BWP': 'Pula de Botsuana',
  'BYN': 'Rublo Bielorrusso',
  'BZD': 'Dólar de Belize',
  // ignore: equal_keys_in_map
  'CAD': 'Dólar Canadense',
  'CDF': 'Franco Congolês',
  // ignore: equal_keys_in_map
  'CHF': 'Franco Suíço',
  // ignore: equal_keys_in_map
  'CLP': 'Peso Chileno',
  // ignore: equal_keys_in_map
  'CNY': 'Yuan Chinês',
  // ignore: equal_keys_in_map
  'COP': 'Peso Colombiano',
  'CRC': 'Colón Costarriquenho',
  'CUP': 'Peso Cubano',
  'CVE': 'Escudo Cabo-Verdiano',
  'CZK': 'Coroa Checa',
  'DJF': 'Franco Djibutiano',
  'DKK': 'Coroa Dinamarquesa',
  'DOP': 'Peso Dominicano',
  'DZD': 'Dinar Argelino',
  'EGP': 'Libra Egípcia',
  'ERN': 'Nakfa Eritreu',
  'ETB': 'Birr Etíope',
  // ignore: equal_keys_in_map
  'EUR': 'Euro',
  'FJD': 'Dólar de Fiji',
  'FKP': 'Libra das Ilhas Malvinas',
  'FOK': 'Coroa Faroesa',
  // ignore: equal_keys_in_map
  'GBP': 'Libra Esterlina',
  'GEL': 'Lari Georgiano',
  'GGP': 'Libra de Guernsey',
  'GHS': 'Cedi Ganês',
  'GIP': 'Libra de Gibraltar',
  'GMD': 'Dalasi Gambiano',
  'GNF': 'Franco Guineense',
  'GTQ': 'Quetzal Guatemalteco',
  'GYD': 'Dólar da Guiana',
  'HKD': 'Dólar de Hong Kong',
  'HNL': 'Lempira Hondurenha',
  'HRK': 'Kuna Croata',
  'HTG': 'Gourde Haitiano',
  'HUF': 'Forint Húngaro',
  'IDR': 'Rupia Indonésia',
  'ILS': 'Novo Shekel Israelense',
  'IMP': 'Libra de Manx',
  'INR': 'Rupia Indiana',
  'IQD': 'Dinar Iraquiano',
  'IRR': 'Rial Iraniano',
  'ISK': 'Coroa Islandesa',
  'JEP': 'Libra de Jersey',
  'JMD': 'Dólar Jamaicano',
  'JOD': 'Dinar Jordaniano',
  // ignore: equal_keys_in_map
  'JPY': 'Iene Japonês',
  'KES': 'Xelim Queniano',
  'KGS': 'Som Quirguiz',
  'KHR': 'Riel Cambojano',
  'KID': 'Dólar de Kiribati',
  'KMF': 'Franco Comorense',
  'KRW': 'Won Sul-Coreano',
  'KWD': 'Dinar Kuwaitiano',
  'KYD': 'Dólar das Ilhas Cayman',
  'KZT': 'Tenge Cazaque',
  'LAK': 'Kip Laosiano',
  'LBP': 'Libra Libanesa',
  'LKR': 'Rupia do Sri Lanka',
  'LRD': 'Dólar Liberiano',
  'LSL': 'Loti do Lesoto',
  'LYD': 'Dinar Líbio',
  'MAD': 'Dirham Marroquino',
  'MDL': 'Leu Moldavo',
  'MGA': 'Ariary Malgaxe',
  'MKD': 'Dinar Macedônio',
  'MMK': 'Kyat de Mianmar',
  'MNT': 'Tugrik Mongol',
  'MOP': 'Pataca de Macau',
  'MRU': 'Ouguiya Mauritana',
  'MUR': 'Rupia Mauriciana',
  'MVR': 'Rufiyaa Maldiva',
  'MWK': 'Kwacha Malauiano',
  // ignore: equal_keys_in_map
  'MXN': 'Peso Mexicano',
  'MYR': 'Ringgit Malaio',
  'MZN': 'Metical Moçambicano',
  'NAD': 'Dólar Namibiano',
  'NGN': 'Naira Nigeriana',
  'NIO': 'Córdoba Nicaraguense',
  'NOK': 'Coroa Norueguesa',
  'NPR': 'Rupia Nepalesa',
  'NZD': 'Dólar Neozelandês',
  'OMR': 'Rial Omanense',
  'PAB': 'Balboa Panamenho',
  // ignore: equal_keys_in_map
  'PEN': 'Sol Peruano',
  'PGK': 'Kina da Papua-Nova Guiné',
  'PHP': 'Peso Filipino',
  'PKR': 'Rupia Paquistanesa',
  'PLN': 'Zloty Polonês',
  // ignore: equal_keys_in_map
  'PYG': 'Guarani Paraguaio',
  'QAR': 'Rial do Catar',
  'RON': 'Leu Romeno',
  'RSD': 'Dinar Sérvio',
  'RUB': 'Rublo Russo',
  'RWF': 'Franco Ruandês',
  'SAR': 'Rial Saudita',
  'SBD': 'Dólar das Ilhas Salomão',
  'SCR': 'Rupia de Seychelles',
  'SDG': 'Libra Sudanesa',
  'SEK': 'Coroa Sueca',
  'SGD': 'Dólar de Singapura',
  'SHP': 'Libra de Santa Helena',
  'SLE': 'Leone de Serra Leoa',
  'SLL': 'Leone de Serra Leoa (antigo)',
  'SOS': 'Xelim Somali',
  'SRD': 'Dólar Surinamês',
  'SSP': 'Libra Sul-Sudanesa',
  'STN': 'Dobra de São Tomé e Príncipe',
  'SYP': 'Libra Síria',
  'SZL': 'Lilangeni Suazi',
  'THB': 'Baht Tailandês',
  'TJS': 'Somoni Tajique',
  'TMT': 'Manat Turcomeno',
  'TND': 'Dinar Tunisiano',
  'TOP': 'Paʻanga de Tonga',
  'TRY': 'Lira Turca',
  'TTD': 'Dólar de Trinidad e Tobago',
  'TVD': 'Dólar de Tuvalu',
  'TWD': 'Novo Dólar Taiuanês',
  'TZS': 'Xelim Tanzaniano',
  'UAH': 'Hryvnia Ucraniana',
  'UGX': 'Xelim Ugandense',
  // ignore: equal_keys_in_map
  'USD': 'Dólar Americano',
  // ignore: equal_keys_in_map
  'UYU': 'Peso Uruguaio',
  'UZS': 'Som Uzbeque',
  // ignore: equal_keys_in_map
  'VES': 'Bolívar Soberano Venezuelano',
  'VND': 'Dong Vietnamita',
  'VUV': 'Vatu de Vanuatu',
  'WST': 'Tala Samoana',
  'XAF': 'Franco CFA da África Central',
  'XCD': 'Dólar do Caribe Oriental',
  'XDR': 'Direitos Especiais de Saque',
  'XOF': 'Franco CFA da África Ocidental',
  'XPF': 'Franco CFP',
  'YER': 'Rial Iemenita',
  'ZAR': 'Rand Sul-Africano',
  'ZMW': 'Kwacha Zambiano',
  'ZWL': 'Dólar do Zimbábue',
};

final Map<String, String> currencySymbols = {
  'USD': '\$',
  'BRL': 'R\$',
  'EUR': '€',
  'GBP': '£',
  'JPY': '¥',
  'CAD': 'C\$',
  'AUD': 'A\$',
  'CHF': 'CHF',
  'CNY': '¥',
  'ARS': '\$',
  'MXN': '\$',
  'CLP': '\$',
  'COP': '\$',
  'UYU': '\$',
  'PYG': '₲',
  'PEN': 'S/',
  'BOB': 'Bs.',
  'VES': 'Bs.S',
  'AED': 'د.إ',
  'AFN': '؋',
  'ALL': 'L',
  'AMD': '֏',
  'ANG': 'ƒ',
  'AOA': 'Kz',
  'AWG': 'ƒ',
  'AZN': '₼',
  'BAM': 'KM',
  'BBD': '\$',
  'BDT': '৳',
  'BGN': 'лв',
  'BHD': '.د.ب',
  'BIF': 'FBu',
  'BMD': '\$',
  'BND': '\$',
  'BSD': '\$',
  'BTN': 'Nu.',
  'BWP': 'P',
  'BYN': 'Br',
  'BZD': 'BZ\$',
  'CDF': 'FC',
  'CVE': '\$',
  'CZK': 'Kč',
  'DJF': 'Fdj',
  'DKK': 'kr',
  'DOP': 'RD\$',
  'DZD': 'د.ج',
  'EGP': '£',
  'ERN': 'Nfk',
  'ETB': 'Br',
  'FJD': 'FJ\$',
  'FKP': '£',
  'FOK': 'kr',
  'GEL': '₾',
  'GGP': '£',
  'GHS': '₵',
  'GIP': '£',
  'GMD': 'D',
  'GNF': 'FG',
  'GTQ': 'Q',
  'GYD': '\$',
  'HKD': 'HK\$',
  'HNL': 'L',
  'HRK': 'kn',
  'HTG': 'G',
  'HUF': 'Ft',
  'IDR': 'Rp',
  'ILS': '₪',
  'IMP': '£',
  'INR': '₹',
  'IQD': 'ع.د',
  'IRR': '﷼',
  'ISK': 'kr',
  'JEP': '£',
  'JMD': 'J\$',
  'JOD': 'JD',
  'KES': 'KSh',
  'KGS': 'сом',
  'KHR': '៛',
  'KID': '\$',
  'KMF': 'CF',
  'KRW': '₩',
  'KWD': 'KD',
  'KYD': '\$',
  'KZT': '₸',
  'LAK': '₭',
  'LBP': 'ل.ل',
  'LKR': 'Rs',
  'LRD': '\$',
  'LSL': 'L',
  'LYD': 'ل.د',
  'MAD': 'د.م.',
  'MDL': 'L',
  'MGA': 'Ar',
  'MKD': 'ден',
  'MMK': 'Ks',
  'MNT': '₮',
  'MOP': 'P',
  'MRU': 'UM',
  'MUR': '₨',
  'MVR': '.ރ',
  'MWK': 'MK',
  'MYR': 'RM',
  'MZN': 'MT',
  'NAD': '\$',
  'NGN': '₦',
  'NIO': 'C\$',
  'NOK': 'kr',
  'NPR': '₨',
  'NZD': '\$',
  'OMR': 'ر.ع.',
  'PAB': 'B/.',
  'PGK': 'K',
  'PHP': '₱',
  'PKR': '₨',
  'PLN': 'zł',
  'QAR': 'ر.ق',
  'RON': 'lei',
  'RSD': 'дин.',
  'RUB': '₽',
  'RWF': 'FRw',
  'SAR': 'ر.س',
  'SBD': '\$',
  'SCR': '₨',
  'SDG': 'ج.س.',
  'SEK': 'kr',
  'SGD': '\$',
  'SHP': '£',
  'SLE': 'Le',
  'SLL': 'Le',
  'SOS': 'Sh',
  'SRD': '\$',
  'SSP': '£',
  'STN': 'Db',
  'SYP': '£',
  'SZL': 'E',
  'THB': '฿',
  'TJS': 'ЅМ',
  'TMT': 'm',
  'TND': 'د.ت',
  'TOP': 'T\$',
  'TRY': '₺',
  'TTD': 'TT\$',
  'TVD': '\$',
  'TWD': 'NT\$',
  'TZS': 'Sh',
  'UAH': '₴',
  'UGX': 'USh',
  'VND': '₫',
  'VUV': 'Vt',
  'WST': 'WS\$',
  'XAF': 'FCFA',
  'XCD': '\$',
  'XDR': 'SDR',
  'XOF': 'CFA',
  'XPF': '₣',
  'YER': '﷼',
  'ZAR': 'R',
  'ZMW': 'ZK',
  'ZWL': '\$',
};
